<?php

declare(strict_types=1);

use HostingerSpace\Analysis\Linker;
use HostingerSpace\Config;
use HostingerSpace\Mysql\DatabaseInfo;
use HostingerSpace\Mysql\DatabaseInventory;
use HostingerSpace\Scanner\SiteScanner;
use HostingerSpace\Transport\LocalTransport;

/**
 * Cree un Dolibarr sur disque, tel qu'il s'installe reellement.
 *
 * @param array<string,string> $overrides
 */
function dolibarrSite(string $racine, string $base, string $sousDossier = 'conf', array $overrides = []): void
{
    $valeurs = [
        'dolibarr_main_db_host' => 'localhost',
        'dolibarr_main_db_port' => '3306',
        'dolibarr_main_db_name' => $base,
        'dolibarr_main_db_prefix' => 'llx_',
        'dolibarr_main_db_user' => $base,
        'dolibarr_main_db_pass' => 'secret-a-ne-jamais-afficher',
        'dolibarr_main_db_type' => 'mysqli',
        'dolibarr_main_data_root' => '/home/u1/documents',
        ...$overrides,
    ];

    $php = "<?php\n//\n// File generated by Dolibarr installer\n//\n";

    foreach ($valeurs as $nom => $valeur) {
        $php .= "\${$nom}='{$valeur}';\n";
    }

    mkdir("{$racine}/{$sousDossier}", 0o775, true);
    file_put_contents("{$racine}/{$sousDossier}/conf.php", $php);
    file_put_contents("{$racine}/filefunc.inc.php", "<?php\ndefine('DOL_VERSION', '14.0.3');\n");
}

test('Un Dolibarr en service n est plus compte comme orphelin', function (): void {
    /*
     * Signale sur une installation reelle : consomable.<domaine> tournait sur
     * une base que l'outil listait en orpheline. Dolibarr ne ressemble a aucun
     * autre — ni « define », ni tableau de configuration, mais des variables
     * prefixees « dolibarr_main_ » dans un conf/conf.php que rien ne lisait.
     * Sa base ressortait donc utilisee par personne : le faux positif exact
     * qui fait supprimer une base pleine.
     */
    $racine = sys_get_temp_dir() . '/hspace-doli-' . bin2hex(random_bytes(6));
    mkdir("{$racine}/domains/consomable.bekatel.org/public_html", 0o775, true);
    dolibarrSite("{$racine}/domains/consomable.bekatel.org/public_html", 'u1_extreme');

    $config = Config::fromArray([
        'mode' => 'local',
        'paths' => ['home' => $racine, 'domains_dir' => $racine . '/domains', 'ignore' => []],
        'analysis' => ['max_depth' => 3],
    ]);

    $sites = (new SiteScanner(new LocalTransport($racine), $config))->scan();

    assertCount(1, $sites);
    assertSame('dolibarr', $sites[0]->app);
    assertSame('14.0.3', $sites[0]->version);

    $declare = $sites[0]->discovered[0];
    assertSame('u1_extreme', $declare->database);
    assertSame('llx_', $declare->tablePrefix);
    assertSame(3306, $declare->port);

    // Le rattachement, qui est tout l'enjeu.
    $inventaire = new DatabaseInventory(
        ['u1_extreme' => new DatabaseInfo('u1_extreme'), 'u1_vieux' => new DatabaseInfo('u1_vieux')],
        probes: [],
        complete: true,
        declared: true,
    );

    $analyse = (new Linker(180))->analyse($sites, $inventaire);

    assertSame(['u1_vieux'], $analyse->orphans, 'la base du Dolibarr en service ne doit pas ressortir orpheline');

    nettoyer($racine);
});

test('Dolibarr est reconnu quand la racine web est au-dessus de htdocs', function (): void {
    // L'autre disposition courante : le sous-domaine pointe sur le dossier
    // parent, et la configuration vit dans htdocs/conf/.
    $racine = sys_get_temp_dir() . '/hspace-doli2-' . bin2hex(random_bytes(6));
    $site = "{$racine}/domains/gestion.exemple.org/public_html";
    mkdir($site, 0o775, true);
    dolibarrSite($site, 'u1_gestion', 'htdocs/conf');

    $config = Config::fromArray([
        'mode' => 'local',
        'paths' => ['home' => $racine, 'domains_dir' => $racine . '/domains', 'ignore' => []],
        'analysis' => ['max_depth' => 3],
    ]);

    $sites = (new SiteScanner(new LocalTransport($racine), $config))->scan();
    $trouve = null;

    foreach ($sites as $site) {
        if ($site->app === 'dolibarr') {
            $trouve = $site;
        }
    }

    assertTrue($trouve !== null, 'le Dolibarr sous htdocs/ doit etre reconnu');
    assertSame('u1_gestion', $trouve->discovered[0]->database);

    nettoyer($racine);
});

test('Un Dolibarr sur un autre moteur ne prete pas a confusion', function (): void {
    // PostgreSQL : la base n'est pas sur le MySQL de l'hebergement, et rien ne
    // doit laisser croire qu'une base MySQL du meme nom est utilisee.
    $racine = sys_get_temp_dir() . '/hspace-doli3-' . bin2hex(random_bytes(6));
    $site = "{$racine}/domains/pg.exemple.org/public_html";
    mkdir($site, 0o775, true);
    dolibarrSite($site, 'u1_pg', 'conf', ['dolibarr_main_db_type' => 'pgsql']);

    $config = Config::fromArray([
        'mode' => 'local',
        'paths' => ['home' => $racine, 'domains_dir' => $racine . '/domains', 'ignore' => []],
        'analysis' => ['max_depth' => 3],
    ]);

    $sites = (new SiteScanner(new LocalTransport($racine), $config))->scan();

    assertSame('dolibarr', $sites[0]->app);
    assertCount(0, $sites[0]->discovered);
    assertContains('pgsql', implode(' ', $sites[0]->notes));

    nettoyer($racine);
});

test('Le mot de passe de Dolibarr n est jamais retenu', function (): void {
    $racine = sys_get_temp_dir() . '/hspace-doli4-' . bin2hex(random_bytes(6));
    $site = "{$racine}/domains/secret.exemple.org/public_html";
    mkdir($site, 0o775, true);
    dolibarrSite($site, 'u1_secret');

    $config = Config::fromArray([
        'mode' => 'local',
        'paths' => ['home' => $racine, 'domains_dir' => $racine . '/domains', 'ignore' => []],
        'analysis' => ['max_depth' => 3],
    ]);

    $sites = (new SiteScanner(new LocalTransport($racine), $config))->scan();
    $inventaire = new DatabaseInventory([], probes: [], complete: false);

    // Le mot de passe sert a ouvrir la base pendant le scan, puis disparait :
    // il ne doit ressortir dans aucun constat ni aucune note.
    $analyse = (new Linker(180))->analyse($sites, $inventaire);
    $texte = json_encode([$sites[0]->notes, $analyse->findings, $analyse->links], JSON_THROW_ON_ERROR);

    assertFalse(str_contains($texte, 'secret-a-ne-jamais-afficher'));

    nettoyer($racine);
});

function nettoyer(string $chemin): void
{
    foreach (glob($chemin . '/*') ?: [] as $entree) {
        is_dir($entree) ? nettoyer($entree) : unlink($entree);
    }

    @rmdir($chemin);
}

test('Une application maison a variables prefixees est rattachee quand meme', function (): void {
    /*
     * La generalisation du cas Dolibarr. Les applications maison nomment leurs
     * variables comme elles l'entendent — « $cfg_db_name », « $app_database ».
     * Exiger un nom exact en faisait autant d'orphelines inventees.
     *
     * Se tromper dans ce sens est sans danger : une base rattachee a tort n'est
     * pas proposee au nettoyage. L'inverse fait supprimer une base en service.
     */
    $racine = sys_get_temp_dir() . '/hspace-maison-' . bin2hex(random_bytes(6));
    $site = "{$racine}/domains/facture.exemple.org/public_html";
    mkdir($site, 0o775, true);

    file_put_contents("{$site}/config.php", <<<'PHP_SRC'
        <?php
        $cfg_db_host = 'localhost';
        $cfg_db_name = 'u1_facture';
        $cfg_db_user = 'u1_facture';
        $cfg_db_password = 'x';
        PHP_SRC);
    file_put_contents("{$site}/index.php", "<?php require __DIR__ . '/config.php';");

    $config = Config::fromArray([
        'mode' => 'local',
        'paths' => ['home' => $racine, 'domains_dir' => $racine . '/domains', 'ignore' => []],
        'analysis' => ['max_depth' => 3],
    ]);

    $sites = (new SiteScanner(new LocalTransport($racine), $config))->scan();
    $inventaire = new DatabaseInventory(
        ['u1_facture' => new DatabaseInfo('u1_facture')],
        probes: [],
        complete: true,
        declared: true,
    );

    assertSame('u1_facture', $sites[0]->discovered[0]->database ?? null);
    assertSame([], (new Linker(180))->analyse($sites, $inventaire)->orphans);

    nettoyer($racine);
});
